language: php

branches:
  except:
    - /^develop/

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
  - php: hhvm-nightly
  - php: hhvm

script: phpunit --configuration phpunit.xml.dist
