language: php

before_install:
  - composer self-update

php:
  - 5.6
  - 7.0
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - composer install

script:
  - phpunit --verbose
