language: php

before_install:
  - composer self-update
  - cp .env.example .env

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

install:
  - composer install

script:
  - php artisan key:generate
  - phpunit --verbose
