#!/usr/bin/env php
<?php
if(strtolower(php_sapi_name()) !== 'cli') {
    die('CLI Request required');
}

if(version_compare(phpversion(), '7.3.0', '<')) {
    die('Requires PHP 7.3 or higher');
}

set_time_limit(0);

use SimPas\Application;

require 'vendor/autoload.php';

try {
    new Application($argv);
} catch (Exception $e) {}
