<?php

return [
    'full_url' => 'http://simpas.devenv/public/',
    'site_title' => 'SimPas Application',
    'site_description_crawlers' => 'SimPas Application',
    'show_index_in_urls' => true,
    'shortcut_icon_url' => '',
    'admin_email' => '',
    'default_geshi_language' => 'Text',
    'site_offline' => false,
    'offline_allowed_ip' => '127.0.0.1',
    'offline_message' => '',
    'offline_message_allow_html' => false,
    'theme' => 'default',
    'max_chars' => 50000,
    'max_size_in_kb' => 512,
    'translations' => false,
    'translation_domain' => 'messages',
    'locale' => [
        'pl',
        'pl_PL'
    ],
    'default_timezone' => 'Europe/Warsaw',
    'charset' => 'UTF-8',
    'gzip_compression' => false,
    'antyflood_enabled' => true,
    'antyflood_delay_in_seconds' => 30,
    'banned_ip' => [
        '8.8.8.8',
        '8.8.8.*'
    ],
    'google_analytics_ua_code' => '',
    'short_url' => false,
    'latest_pastes' => 20,
    'antispam_enabled' => false,
    'antispam_case_sensitive' => false,
    'author_website_enabled' => true,
    'delete_expired_pastes' => true,
    'cookie_path' => '',
    'cookie_domain' => '',
    'cookie_secure' => false,
    'hot_paste' => 1500,
    'show_cookies_info' => true,
];
